### ISSUE TITLE
Consider providing additional detail to the listing at the Umbraco marketplace

### ISSUE THREAD

**Issue by AndyButland** [huwred/MediaWizForums#2]
Hi Huw - I'm just doing a review of packages listed at the Umbraco Marketplace and noticed that whilst you are providing additional information via the file at https://umbraco.themediawizards.co.uk/umbraco-marketplace.json, you haven't included a category.  This is fine... but it does mean there's a route by which your package won't be found (i.e. when visitors click through the category links).

If you want to add one, you can do so via this file via adding:

```
"Category": "Developer Tools",
```

Or whatever you think is most appropriate from the list [shown here](https://marketplace.umbraco.com/listing).

**Comment by huwred** [comment]
Hi Andy,
Thanks for the headsup, I will update my json file
