### ISSUE TITLE
Does this work on Unmbraco 11.4.0 

### ISSUE THREAD

**Issue by jbfranklin** [huwred/MediaWizForums#3]
Huw,

I installed MediaWizForums on Unmbraco 11.4.0 and when I go to it I get a 404. (https://localhost:44357/forums/)

Here is my back office:
![image](https://github.com/huwred/MediaWizForums/assets/11843078/b5c885a7-b0a4-46c1-81ec-157dbc12e43e)

Here is the 404:
![image](https://github.com/huwred/MediaWizForums/assets/11843078/81a71091-13ad-47b8-a2c4-37f26909318d)

-Jason

**Comment by huwred** [comment]
Hi,
I just fired up a blank 11.4 and installed the forum package, looks like it works just fine

<img width="816" alt="image" src="https://github.com/huwred/MediaWizForums/assets/4870243/d8da89f3-17dd-4a49-82b2-2b19570c054e">

**Comment by huwred** [comment]
Tested and working in U11
