### ISSUE TITLE
Login partial is always shown.

### ISSUE THREAD

**Issue by BramvdBogaard** [huwred/MediaWizForums#6]
I'm currently using the package on version 10.6.1.-rc1.2 for Umbraco 10.6.1 and for some reason the login partial is always shown. 
When I go to the /register URL the register page is not shown, instead the login partial is shown, leading to people being unable to register.

Is there a fix for this issue? I've been unable to find out where in the code this issue originates.

**Comment by huwred** [comment]
could you post a screenshot and I will take a look

**Comment by BramvdBogaard** [comment]
Thanks for the quick response. As you can see in this screenshot I'm looking at the register page. I've also just figured out that I can actually load the register page while I'm logged in, so perhaps there is something going on in the login check?

![afbeelding](https://github.com/huwred/MediaWizForums/assets/33619813/59fe27a6-7d5f-4014-8277-9eb154b7d89e)

**Comment by huwred** [comment]
looks more like some sort of routing issue so the register link is loading the login page not the register page, is the page link /register?

**Comment by BramvdBogaard** [comment]
Yes the url is indeed /register. The login partial is always shown, so not just for /register but also for /forgotpassword. I've got these settings in Umbraco for the /register page: 
![afbeelding](https://github.com/huwred/MediaWizForums/assets/33619813/c32b4a46-4959-48cb-a172-a55b4a588116)

**Comment by huwred** [comment]
I'm a bit baffled as to what is causing this, I don't suppose you have it hosted anywher I could take a look?

**Comment by BramvdBogaard** [comment]
Not really to be honest. The other weird problem is that it actually works on our pre-production Azure environment but not on an IIS testing environment on a Windows 2012 server. I guess I'll have to try and figure out how that is possible. Have you seen this issue before?

**Comment by BramvdBogaard** [comment]
I've just noticed that we had restricted private access on our testing and local environments while we did not have this on our pre production environment. This was the issue, the correct partials are now loaded correctly! :)

**Comment by huwred** [comment]
Glad you got it sorted
