### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Clyde69** [huwred/MediaWizForums#7]
Hi there, these aren't issues as much as questions.

1) Can I change the Umbraco member type you use to one that my site already has? If it means changing code, I can do that & share but I can't see where it's set at this time.
2) Is there a way to have approved posts only show?

Cheers
Chris

**Comment by huwred** [comment]
You could change the member type, It is used in just 3 places I believe

1. ForumMemberController.cs
2. Register.cshtml
3. ResetPassword.cshtml

It would be possible to add a post approval flag/process but that would require a few more changes.

**Comment by huwred** [comment]
@Clyde69  I just published an update which will allow you to set the membertype alias in appsetting

https://www.nuget.org/packages/MediaWiz.Forums/13.0.1

**Comment by Clyde69** [comment]
@huwred thank you, you're a legend sir!

**Comment by huwred** [comment]
I'm working on an approval process, but may take a few days to complete
